# Generated by Django 4.2.11 on 2024-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.TextField()),
                ('points', models.IntegerField()),
                ('app_cat', models.CharField(max_length=100)),
                ('app_sub_cat', models.CharField(max_length=100)),
                ('app_img', models.ImageField(upload_to='app_images/')),
            ],
        ),
    ]
