# Generated by Django 4.2.11 on 2024-05-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_app_detail_app_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_detail',
            name='app_img',
            field=models.ImageField(blank=True, null=True, upload_to='app_images/'),
        ),
    ]
