# Generated by Django 4.2.11 on 2024-05-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_app_detail_app_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_detail',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
