# Generated by Django 4.2.11 on 2024-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_app_detail_app_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_detail',
            name='app_img',
            field=models.ImageField(default='app_images/default.jpg', upload_to='app_images/'),
        ),
    ]
